apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: {{ .User }}-eventsource
spec:
  webhook:
{{- range .Event }}
    {{ .name }}:
      endpoint: /{{ .name }}
      method: POST
{{- end }}