{{- range .Service }}
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Name }}
  namespace: {{ $.User }}
spec:
  template:
    spec:
      containers:
        - image: {{ .Image }}
---
{{- end }}