apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: {{ .User }}-sensor
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
  {{- range .Event }}
    - name: {{ .Name }}
      eventSourceName: event-source-{{ .Name }}
      eventName: {{ .Name }}
  {{- end }}
  triggers:
  {{- range $index, $logic := .EventLogic }}
    - template:
        name: trigger-workflow-{{ $index }}
        conditions: "{{ $logic.Condition }}"
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: workflow-{{ $logic.Service }}-
              spec:
                entrypoint: main
                workflowTemplateRef:
                  name: {{ $logic.Service }}-workflow-template
  {{- end }}