apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ .User }}-workflow-template
  namespace: {{ .User }}
spec:
  templates:
  - name: main
    steps:
    {{- range .Service }}
    - - name: {{ .Name }}
        template: {{ .Name }}
    {{- end }}

  {{- range .Service }}
  - name: {{ .Name }}
    http:
      url: http://{{ .Name }}.{{ $.User }}.svc.cluster.local
      method: POST
      headers:
      - name: Content-Type
        value: application/json
  {{- end }}